version: "3"
services:
  dealer-offer-api: # ШЛЮЗ - через него идет вся работа
#    image: nikitasologub/dealer-offer-api:v0031
    image: api
    build: .
    container_name: dealer-offer-api
    ports:
      - "9080:9080"
#    depends_on:
#      - rabbitmq
#      - minio
#      - postgres
    environment:
      RABBIT_HOST: "rbmqtest-01-msk.inner.alfaleasing.ru" # (dev- rbmqtest-01-msk.inner.alfaleasing.ru) (local - rabbitmq) (http://rbmqtest-01-msk.inner.alfaleasing.ru/)
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "nosologub" # (dev- nosologub) (local - guest)
      RABBIT_PASSWORD: "fuj53lWR816" # (dev- fuj53lWR816) (local - guest)
      MINIO_SERVER_HOST: https://storage.yandexcloud.net/ # (local- http://minio:9000/)
      MINIO_BUCKET: svc-yc-car-search
      MINIO_CLIENT_ID: YCAJEpPp9OIYu7W8v8kkCwlci
      MINIO_CLIENT_SECRET: YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2
      DRIVER_CLASS_NAME: org.postgresql.Driver
      URL: jdbc:postgresql://lkpgdb-comm-test.inner.alfaleasing.ru:5432/car_search_platform_db
      USERNAME: car_search_platform_db_user
      PASSWORD: FP8VCNJ8gvU7YzGi
    networks:
      - application-network

  dealer-offer-web-portal: # микросервис для загрузки excel файлов
    image: nikitasologub/dealer-offer-web-portal:v0021
    container_name: dealer-offer-web-portal
    ports:
      - "15072:15072"
    networks:
      - application-network
    environment:
      DEALER_OFFER_API_URL: "http://dealer-offer-api:9080"

#  avtomir-dealer-provider: # микросервис для похода на Автомир
#    image: loverloser1804/avtomir-self-dealer-provider:422
##    image: avtomir
#    container_name: avtomir-self-loading-provider
#    ports:
#      - "9079:9079"
#    environment:
#      DEALER_OFFER_API_HOST: "http://dealer-offer-api:9080"
#    networks:
#      - application-network

#  postgres:
#    image: postgres
#    container_name: postgres
#    environment:
#      POSTGRES_DB: habrdb
#      POSTGRES_USER: habrpguser
#      POSTGRES_PASSWORD: pgpwd4habr
#    ports:
#      - "5432:5432"
#    networks:
#      - application-network

#  rabbitmq: # шина будет посылать сюда сообщения
#    image: rabbitmq:3.10-management
#    container_name: rabbitmq
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBIT_PORT: 5672
#      RABBIT_USERNAME: guest
#      RABBIT_PASSWORD: guest
#    networks:
#      - application-network

#  minio: # шина будет записывать сюда json файлы
#    image: minio/minio:latest
#    container_name: minio
#    hostname: minio
#    command: server --console-address ":9001" /data/
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_BUCKET: svc-yc-car-search
#      MINIO_ROOT_USER: YCAJEpPp9OIYu7W8v8kkCwlci
#      MINIO_ROOT_PASSWORD: YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2
#    networks:
#      - application-network
#    volumes:
#      - /data/minio/data:/export

networks:
  application-network:
    driver: bridge
