version: "3"
services:
  dealer-offer-api: # ШЛЮЗ - через него идет вся работа
#    image: nikitasologub/dealer-offer-api:v0031
    image: api
    build: .
    container_name: dealer-offer-api
    ports:
      - "15073:15073"
    depends_on:
      - rabbitmq
      - minio
      - postgres
    environment:
      RABBIT_HOST: "rabbitmq" # (dev- rbmqtest-01-msk.inner.alfaleasing.ru) (http://rbmqtest-01-msk.inner.alfaleasing.ru/)
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest" # (dev- nosologub)
      RABBIT_PASSWORD: "guest" # (dev- fuj53lWR816)
      MINIO_ROOT_URL: http://minio:9000/ # (dev- https://storage.yandexcloud.net/)
      MINIO_BUCKET: svc-yc-car-search
      MINIO_ROOT_USER: YCAJEpPp9OIYu7W8v8kkCwlci
      MINIO_ROOT_PASSWORD: YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2
      DRIVER_CLASS_NAME: org.postgresql.Driver
#      URL: jdbc:postgresql://lkpgdb-comm-test.inner.alfaleasing.ru:5432/car_search_platform_db
#      USERNAME: car_search_platform_db_user
#      PASSWORD: FP8VCNJ8gvU7YzGi
    networks:
      - application-network

  dealer-offer-web-portal: # микросервис для загрузки excel файлов
    image: nikitasologub/dealer-offer-web-portal:v0021
    container_name: dealer-offer-web-portal
    ports:
      - "15072:15072"
    networks:
      - application-network
    environment:
      DEALER_OFFER_API_URL: "http://dealer-offer-api:15073"

#  avtomir-dealer-provider: # микросервис для похода на Автомир
#    image: loverloser1804/avtomir-self-dealer-provider:422
##    image: avtomir
#    container_name: avtomir-self-loading-provider
#    ports:
#      - "9079:9079"
#    environment:
#      DEALER_OFFER_API_HOST: "http://dealer-offer-api:15073"
#    networks:
#      - application-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - "5432:5432"
    networks:
      - application-network

  rabbitmq: # шина будет посылать сюда сообщения
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    networks:
      - application-network

  minio: # шина будет записывать сюда json файлы
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BUCKET: svc-yc-car-search
      MINIO_ROOT_USER: YCAJEpPp9OIYu7W8v8kkCwlci
      MINIO_ROOT_PASSWORD: YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2
    networks:
      - application-network
    volumes:
      - /data/minio/data:/export

networks:
  application-network:
    driver: bridge
