version: "3"
services:
  dealer-offer-api: # ШЛЮЗ - через него идет вся работа
    image: dealer-offer-api
    container_name: dealer-offer-api
    ports:
      - "15073:15073"
    depends_on:
      - rabbitmq
      - minio
    environment:
      DEALER_OFFER_WEB_PORTAL_URL: "http://dealer-offer-web-portal:15072"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
      MINIO_ROOT_URL: http://minio:9000/
      MINIO_BUCKET: retrobucket
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    networks:
      - application-network

  dealer-offer-web-portal: # микросервис для работы с excel и xml файлами
    image: dealer-offer-web-portal
    container_name: dealer-offer-web-portal
    ports:
      - "15072:15072"
    networks:
      - application-network

  avtomir-dealer-provider: # микросервис для похода на Автомир
    image: avtomir-dealer-provider
    container_name: avtomir-dealer-provider
    ports:
      - "18420:18420"
    environment:
      DEALER_OFFER_API_URL: "http://dealer-offer-api:15073"
    networks:
      - application-network

  rabbitmq: # шина будет посылать сюда сообщения
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    networks:
      - application-network

  minio: # шина будет записывать сюда json файлы
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BUCKET: retrobucket
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    networks:
      - application-network
    volumes:
      - /data/minio/data:/export

networks:
  application-network:
    driver: bridge
