spring:
  application.name: dealer-offer-api
#  profiles.active: logging_to_console
  liquibase:
    default-schema: public
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://lkpgdb-comm-test.inner.alfaleasing.ru:5432/car_search_platform_db}
    username: ${POSTGRES_USER:car_search_platform_db_user}
    password: ${POSTGRES_PASSWORD:FP8VCNJ8gvU7YzGi}
  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.identity-server.url}/.well-known/openid-configuration/jwks
  cloud:
    stream:
      rabbit:
        bindings:
          dealer_offer_api:
            producer:
              exchangeType: direct
              routing-key-expression: "'new-offers-list.event.create'"
          c_sharp_exchange:
            consumer:
              exchangeType: direct
              queueNameGroupOnly: true
              binding-routing-key: "offer-result.event.create"
      bindings:
        dealer_offer_api:
          destination: dealer-offer-api
          group: dealer-offer-api.to.offer-agrigation-service.new-offers-list
          binder: rabbit
        c_sharp_exchange:
          destination: offer-agrigation-service
          group: offer-agrigation-service.to.dealer-offer-api
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                deliveryMode: ${DELIVERY_MODE:2}
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: ${RABBIT_VHOST:/}

app:
  identity-server:
    url: ${IDENTITY_SERVER_HOST:https://identity-stage.alfaleasing.ru}
    client-id: ${IDENTITY_CLIENT_ID:c-dealer-offer-api}
    client-secret: ${IDENTITY_CLIENT_SECRET:bc3d98b6-9e30-8045-4732-9a513321c514}
    scope: ${IDENTITY_SCOPE:}
  minio:
    url: ${MINIO_SERVER_HOST:https://https://storage.yandexcloud.net/}
    bucket: ${MINIO_BUCKET:svc-yc-car-search}
    access-key: ${MINIO_CLIENT_ID:YCAJEpPp9OIYu7W8v8kkCwlci}
    secret-key: ${MINIO_CLIENT_SECRET:YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2}

jwks.public-key.time-to-live: ${JWKS_PUBLIC_KEY_TTL:300}

logging:
  level:
    ru:
      alfaleasing: ${LOGGING_LEVEL:INFO}
    org:
      springframework:
        security: INFO

server:
  port: 9080
  servlet.context-path: /dealer-offer-api