server:
  port: 15073
  servlet.context-path: /dealer-offer-API

client:
  dealer-offer-web-portal:
    url: 'http://localhost:15072/dealer-offer-web-portal'

minio:
  url: http://localhost:9000/ # Minio Host (by default - https://play.min.io)
  bucket: retrobucket # Minio Bucket name for your application (for example 00000qweqwe)
  access-key: Q3AM3UQ867SPQQA43P2F # Minio access key (login)
  secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG # Minio secret key (password)

spring:
  cloud:
    stream:
      bindings:
        dealer-car-stock:
          destination: dealer-car-stock-exchange
          binder: rabbit




      binders:
        rabbit:
          type: rabbit
          environment:
            username: ${RABBIT_USERNAME:guest}
            password: ${RABBIT_PASSWORD:guest}
            virtual-host: ${RABBIT_VHOST:/}
            host: ${RABBIT_HOST:localhost}
            port: ${RABBIT_PORT:5672}

#logging:
#  level:
#    ru:
#      alfaleasing: ${LOGGING_LEVEL:INFO}
#      alfaleasing.logging:
#        http: ${LOGGING_LEVEL:INFO}