server:
  port: 15073
  servlet.context-path: /dealer-offer-API

client:
  dealer-offer-web-portal:
    url: 'http://localhost:15072/dealer-offer-web-portal'

#logging:
#  level:
#    ru:
#      alfaleasing: ${LOGGING_LEVEL:INFO}
#      alfaleasing.logging:
#        http: ${LOGGING_LEVEL:INFO}