server:
  port: 15073
  servlet.context-path: /dealer-offer-API

client:
  dealer-offer-web-portal:
    url: ${DEALER_OFFER_WEB_PORTAL_URL:http://localhost:15072}/dealer-offer-web-portal/v1/dealer

minio:
  url: ${MINIO_ROOT_URL:https://localhost:9000/} #(by default - https://play.min.io)
  bucket: ${MINIO_BUCKET:retrobucket}
  access-key: ${MINIO_ROOT_USER:Q3AM3UQ867SPQQA43P2F}
  secret-key: ${MINIO_ROOT_PASSWORD:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}

spring:
  cloud:
    stream:
      bindings:
        dealer-car-stock:
          destination: dealer-car-stock-exchange
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            virtual-host: ${RABBIT_VHOST:/}
            port: ${RABBIT_PORT:5672}
            username: ${RABBIT_USERNAME:guest}
            password: ${RABBIT_PASSWORD:guest}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

#logging:
#  level:
#    ru:
#      alfaleasing: ${LOGGING_LEVEL:INFO}
#      alfaleasing.logging:
#        http: ${LOGGING_LEVEL:INFO}