spring:
  application.name: dealer-offer-api
  liquibase:
    default-schema: public
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://lkpgdb-comm-test.inner.alfaleasing.ru:5432/car_search_platform_db}
    username: ${POSTGRES_USER:car_search_platform_db_user}
    password: ${POSTGRES_PASSWORD:FP8VCNJ8gvU7YzGi}
  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
  cloud:
    stream:
      rabbit:
        bindings:
          dealer_offer_api:
            producer:
              exchangeType: direct
              routing-key-expression: "'new-offers-list.event.create'"
          c_sharp_exchange:
            consumer:
              exchangeType: direct
              queueNameGroupOnly: true
              binding-routing-key: "offer-result.event.create"
      bindings:
        dealer_offer_api:
          destination: dealer-offer-api
          group: dealer-offer-api.to.offer-agrigation-service.new-offers-list
          binder: rabbit
        c_sharp_exchange:
          destination: offer-agrigation-service
          group: offer-agrigation-service.to.dealer-offer-api
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                deliveryMode: ${DELIVERY_MODE:2}
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: ${RABBIT_VHOST:/}

app:
  minio:
    url: ${MINIO_ROOT_URL:https://https://storage.yandexcloud.net/}
    bucket: ${MINIO_BUCKET:svc-yc-car-search}
    access-key: ${MINIO_ROOT_USER:YCAJEpPp9OIYu7W8v8kkCwlci}
    secret-key: ${MINIO_ROOT_PASSWORD:YCM655s5lED4alDInim6hBpcbmBqOPO7xk-JLVh2}

logging:
  level:
    ru:
      alfaleasing: ${LOGGING_LEVEL:INFO}
    org:
      springframework:
        security: INFO

server:
  port: 9080
  servlet.context-path: /dealer-offer-api